/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: 'ap-south-1',
	aws_cloud_logic_custom: [
		{
			name: 'mainApi',
			endpoint: 'https://0nb9pkbpc4.execute-api.ap-south-1.amazonaws.com/staging',
			region: 'ap-south-1',
		},
	],
	aws_dynamodb_all_tables_region: 'ap-south-1',
	aws_dynamodb_table_schemas: [
		{
			tableName: 'channel-staging',
			region: 'ap-south-1',
		},
	],
}

export default awsmobile
